Repository GoodRequest/GoodNetworking, pull requests merged in 2024-01, with the labels that each got.

#4 feat: Refactoring
  Sources/GoodNetworking/Endpoint.swift
  Sources/GoodNetworking/GREndpointManagerProtocol.swift
  Sources/GoodNetworking/GRImageDownloader.swift
  Sources/GoodNetworking/GRSession.swift
  Sources/GoodNetworking/GRSessionLogger.swift
  Sources/GoodNetworking/NetworkSession.swift
  Sources/GoodNetworking/NetworkSessionConfiguration.swift
  Sources/GoodNetworking/URLExtensions.swift
Labels: documentation, enhancement

#5 feat: GoodNetworking + SwiftUI dynamic wrappers
  README.md
  Sources/GoodNetworking/Extensions/AFErrorExtensions.swift
  Sources/GoodNetworking/Extensions/ArrayEncoding.swift
  Sources/GoodNetworking/Extensions/CodableExtensions.swift
  Sources/GoodNetworking/Extensions/DataRequestExtensions.swift
  Sources/GoodNetworking/Extensions/URLExtensions.swift
  Sources/GoodNetworking/GRImageDownloader.swift
  Sources/GoodNetworking/Models/Endpoint.swift
  Sources/GoodNetworking/Models/Query.swift
  Sources/GoodNetworking/Models/Resource.swift
  Sources/GoodNetworking/Session/GRSessionLogger.swift
  Sources/GoodNetworking/Session/NetworkSession.swift
  Sources/GoodNetworking/Session/NetworkSessionConfiguration.swift
  Sources/GoodNetworking/Wrapper/Fetch.swift
  Sources/GoodNetworking/Wrapper/Observable.swift
  Sources/GoodNetworking/Wrapper/Post.swift
  Sources/GoodNetworking/Wrapper/Remote.swift
  Tests/GoodNetworkingTests/ArrayEncodingTests.swift
  Tests/GoodNetworkingTests/Endpoint.swift
Labels: enhancement

#7 feat: Added pretty print and OSLog options
  GoodNetworking-Sample/GoodNetworking-Sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GoodNetworking-Sample/GoodNetworking-Sample/Managers/RequestManager/Endpoint.swift
  GoodNetworking-Sample/GoodNetworking-Sample/Managers/RequestManager/RequestManager.swift
  Sources/GoodNetworking/Session/GRSessionLogger.swift
  Sources/GoodNetworking/Session/Logger/LoggingEventMonitor.swift
  Sources/GoodNetworking/Session/Logger/OSLogSessionLogger.swift
  Sources/GoodNetworking/Session/Logger/PrintLogger.swift
  Sources/GoodNetworking/Session/Logger/SessionLogger.swift
  Sources/GoodNetworking/Session/NetworkSession.swift
  Sources/GoodNetworking/Session/NetworkSessionConfiguration.swift
  Sources/GoodNetworking/Wrapper/Remote.swift
Labels: enhancement

#8 fix: Make Loggers Public
  Sources/GoodNetworking/Session/Logger/LoggingEventMonitor.swift
  Sources/GoodNetworking/Session/Logger/OSLogLogger.swift
  Sources/GoodNetworking/Session/Logger/PrintLogger.swift
  Sources/GoodNetworking/Session/NetworkSessionConfiguration.swift
Labels: bug
